export const productData = [
    {
        id: 1,
        thumbnail: '/images/products/product-1.jpg',
        prodcut_album: ['/images/products/product-1.jpg', '/images/products/product-2.jpg'],
        title: "Memento 2.0",
        price: "134.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "2.5",
    },
    {
        id: 2,
        thumbnail: '/images/products/product-2.jpg',
        prodcut_album: ['/images/products/product-1.jpg', '/images/products/product-2.jpg'],
        title: "SX Bathtubs",
        price: "499.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "5",
    },
    {
        id: 3,
        thumbnail: '/images/products/product-3.jpg',
        prodcut_album: ['/images/products/product-2.jpg', '/images/products/product-1.jpg'],
        title: "NOKEN - TONO",
        price: "249.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "2.0",
    },
    {
        id: 4,
        thumbnail: '/images/products/product-4.jpg',
        prodcut_album: ['/images/products/product-3.jpg', '/images/products/product-2.jpg'],
        title: "NOKEN - TONO",
        price: "249.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "4.5",
    },
    {
        id: 5,
        thumbnail: '/images/products/product-5.jpg',
        prodcut_album: ['/images/products/product-4.jpg', '/images/products/product-1.jpg'],
        title: "NOKEN - TONO",
        price: "249.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "4.5",
    },
    {
        id: 6,
        thumbnail: '/images/products/product-6.jpg',
        prodcut_album: ['/images/products/product-4.jpg', '/images/products/product-2.jpg'],
        title: "NOKEN - TONO",
        price: "249.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "4.5",
    },

    {
        id: 7,
        thumbnail: '/images/products/product-3.jpg',
        prodcut_album: ['/images/products/product-2.jpg', '/images/products/product-1.jpg'],
        title: "NOKEN - TONO",
        price: "249.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "2.0",
    },
    {
        id: 8,
        thumbnail: '/images/products/product-4.jpg',
        prodcut_album: ['/images/products/product-3.jpg', '/images/products/product-2.jpg'],
        title: "NOKEN - TONO",
        price: "249.99",
        product_overview: "The Ratio Pendant Lamp featurees a wide lampshade, referring  the bold and elegant shape  classic metal penwdants. The lamp to features a spun steel shade with a seweamlessly embedded LED module.",
        rating: "4.5",
    },

]